create table category (id integer generated by default as identity, name varchar(255), primary key (id));
create table product (id integer generated by default as identity, name varchar(255), category_id integer, primary key (id));
--alter table product add constraint FK1mtsbur82frn64de7balymq9s foreign key (category_id) references category;